=== au-research/ANDS-Vocabs-Toolkit/src/test/resources/deploy/test/dbunit-toolkit-export-choice.dtd
<!ELEMENT dataset (
   (ACCESS_POINTS|
    LOG|
    RELATED|
    RESOURCE_MAP|
    RESOURCE_OWNER_HOSTS|
    TASK|
    TODO|
    VERSIONS|
    VOCABULARIES)*)>

<!ELEMENT ACCESS_POINTS EMPTY>
<!ATTLIST ACCESS_POINTS
    ID CDATA #IMPLIED
    PORTAL_DATA CDATA #IMPLIED
    TOOLKIT_DATA CDATA #IMPLIED
    TYPE CDATA #IMPLIED
    VERSION_ID CDATA #IMPLIED
>

<!ELEMENT LOG EMPTY>
<!ATTLIST LOG
    ID CDATA #IMPLIED
    CLASS CDATA #IMPLIED
    MESSAGE CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT RELATED EMPTY>
<!ATTLIST RELATED
    ID CDATA #IMPLIED
    DATA CDATA #IMPLIED
    RELATION CDATA #IMPLIED
    SLUG CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    TYPE CDATA #IMPLIED
>

<!ELEMENT RESOURCE_MAP EMPTY>
<!ATTLIST RESOURCE_MAP
    ID CDATA #IMPLIED
    ACCESS_POINT_ID CDATA #IMPLIED
    DEPRECATED CDATA #IMPLIED
    IRI CDATA #IMPLIED
    OWNED CDATA #IMPLIED
    RESOURCE_TYPE CDATA #IMPLIED
>

<!ELEMENT RESOURCE_OWNER_HOSTS EMPTY>
<!ATTLIST RESOURCE_OWNER_HOSTS
    ID CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    HOST CDATA #IMPLIED
    OWNER CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
>

<!ELEMENT TASK EMPTY>
<!ATTLIST TASK
    ID CDATA #IMPLIED
    PARAMS CDATA #IMPLIED
    RESPONSE CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    VERSION_ID CDATA #IMPLIED
    VOCABULARY_ID CDATA #IMPLIED
>

<!ELEMENT TODO EMPTY>
<!ATTLIST TODO
    ID CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    SUMMARY CDATA #IMPLIED
>

<!ELEMENT VERSIONS EMPTY>
<!ATTLIST VERSIONS
    ID CDATA #IMPLIED
    DATA CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    VOCAB_ID CDATA #IMPLIED
>

<!ELEMENT VOCABULARIES EMPTY>
<!ATTLIST VOCABULARIES
    ID CDATA #IMPLIED
    CREATED_DATE CDATA #IMPLIED
    DATA CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    LICENCE CDATA #IMPLIED
    MODIFIED_DATE CDATA #IMPLIED
    MODIFIED_WHO CDATA #IMPLIED
    OWNER CDATA #IMPLIED
    POOL_PARTY_ID CDATA #IMPLIED
    SLUG CDATA #IMPLIED
    STATUS CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    USER_OWNER CDATA #IMPLIED
>

=== au-research/ANDS-Vocabs-Toolkit/src/test/resources/deploy/test/tests/au.org.ands.vocabs.toolkit.test.arquillian.AllArquillianTests.testJsonTreeTransformProvider1/input-dbunit.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "../../dbunit-toolkit-export-choice.dtd" >
<dataset>
  <VOCABULARIES
      ID="1"
      OWNER="ands"
      TITLE="testJsonTreeTransformProvider1"
      SLUG="testjsontreetransformprovider1"
      />
  <VERSIONS
      ID="1"
      VOCAB_ID="1"
      TITLE="v1" />
  <ACCESS_POINTS/>
  <TASK
      ID="1"
      VOCABULARY_ID="1"
      VERSION_ID="1"
      PARAMS="[
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''src/test/resources/input/au.org.ands.vocabs.toolkit.test.arquillian.AllArquillianTests.testJsonTreeTransformProvider1/test-data1.ttl''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''JsonTree''
                }
              ]"
      />
  <TASK
      ID="2"
      VOCABULARY_ID="1"
      VERSION_ID="1"
      PARAMS="[
                {
                  ''type'': ''UNHARVEST'',
                  ''provider_type'': ''File''
                },
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''src/test/resources/input/au.org.ands.vocabs.toolkit.test.arquillian.AllArquillianTests.testJsonTreeTransformProvider1/test-data2.ttl''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''JsonTree''
                }
              ]"
      />
  <TASK
      ID="3"
      VOCABULARY_ID="1"
      VERSION_ID="1"
      PARAMS="[
                {
                  ''type'': ''UNHARVEST'',
                  ''provider_type'': ''File''
                },
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''src/test/resources/input/au.org.ands.vocabs.toolkit.test.arquillian.AllArquillianTests.testJsonTreeTransformProvider1/test-data3.ttl''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''JsonTree''
                }
              ]"
      />
  <TASK
      ID="4"
      VOCABULARY_ID="1"
      VERSION_ID="1"
      PARAMS="[
                {
                  ''type'': ''UNHARVEST'',
                  ''provider_type'': ''File''
                },
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''src/test/resources/input/au.org.ands.vocabs.toolkit.test.arquillian.AllArquillianTests.testJsonTreeTransformProvider1/test-data4.ttl''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''JsonTree''
                }
              ]"
      />
</dataset>

=== au-research/ANDS-Vocabs-Toolkit/src/test/resources/deploy/test/tests/au.org.ands.vocabs.toolkit.test.arquillian.AllArquillianTests.testResolveIRILookupIRI1/input-dbunit.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "../../dbunit-toolkit-export-choice.dtd" >
<dataset>
  <VOCABULARIES
      ID="1"
      OWNER="ands"
      TITLE="testResourceMapTransformProvider1"
      SLUG="testresourcemaptransformprovider1"
      STATUS="current"
      />
  <VERSIONS
      ID="1"
      VOCAB_ID="1"
      TITLE="v1"
      STATUS="current"
      />
  <RESOURCE_OWNER_HOSTS
      ID="1"
      START_DATE="2016-09-16"
      END_DATE="9999-12-01"
      OWNER="ands"
      HOST="vocab.owner.org"
      />

  <ACCESS_POINTS ID="5" PORTAL_DATA="{&quot;uri&quot;:&quot;http://localhost:8125/ANDS-Vocabs-Toolkit/download/5/test-data1.ttl&quot;,&quot;format&quot;:&quot;TTL&quot;}" TOOLKIT_DATA="{&quot;path&quot;:&quot;ands_vocabs/vocabs/ands/testresourcemaptransformprovider1/v1/harvest_data/test-data1.ttl&quot;}" TYPE="file" VERSION_ID="1"/>
  <ACCESS_POINTS ID="6" PORTAL_DATA="{&quot;uri&quot;:&quot;http://testing-host.org.au/repository/api/sparql/ands_testresourcemaptransformprovider1_v1&quot;,&quot;source&quot;:&quot;system&quot;}" TOOLKIT_DATA="{}" TYPE="apiSparql" VERSION_ID="1"/>
  <ACCESS_POINTS ID="7" PORTAL_DATA="{&quot;uri&quot;:&quot;http://localhost:8125/ANDS-Vocabs-Toolkit/download/7/ands_testresourcemaptransformprovider1_v1.&quot;}" TOOLKIT_DATA="{&quot;uri&quot;:&quot;http://localhost:8125/openrdf-sesame/repositories/ands_testresourcemaptransformprovider1_v1&quot;}" TYPE="sesameDownload" VERSION_ID="1"/>
  <ACCESS_POINTS ID="8" PORTAL_DATA="{&quot;uri&quot;:&quot;http://testing-host.org.au/repository/api/lda/ands/testresourcemaptransformprovider1/v1&quot;,&quot;source&quot;:&quot;system&quot;}" TOOLKIT_DATA="{}" TYPE="sissvoc" VERSION_ID="1"/>

  <RESOURCE_MAP ID="1" ACCESS_POINT_ID="8" DEPRECATED="false" IRI="http://vocab.owner.org/def/vocab1/1" OWNED="true" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
  <RESOURCE_MAP ID="2" ACCESS_POINT_ID="8" DEPRECATED="true" IRI="http://vocab.owner.org/def/vocab1/5" OWNED="true" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
  <RESOURCE_MAP ID="3" ACCESS_POINT_ID="8" DEPRECATED="false" IRI="http://some.other.org/def/vocab1/1" OWNED="false" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
  <RESOURCE_MAP ID="4" ACCESS_POINT_ID="8" DEPRECATED="true" IRI="http://some.other.org/def/vocab1/5" OWNED="false" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
  <RESOURCE_MAP ID="5" ACCESS_POINT_ID="8" DEPRECATED="false" IRI="http://vocab.owner.org/def/vocab1/2" OWNED="true" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#Collection"/>
  <RESOURCE_MAP ID="6" ACCESS_POINT_ID="8" DEPRECATED="true" IRI="http://vocab.owner.org/def/vocab1/6" OWNED="true" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#Collection"/>
  <RESOURCE_MAP ID="7" ACCESS_POINT_ID="8" DEPRECATED="false" IRI="http://some.other.org/def/vocab1/2" OWNED="false" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#Collection"/>
  <RESOURCE_MAP ID="8" ACCESS_POINT_ID="8" DEPRECATED="true" IRI="http://some.other.org/def/vocab1/6" OWNED="false" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#Collection"/>
  <RESOURCE_MAP ID="9" ACCESS_POINT_ID="8" DEPRECATED="false" IRI="http://vocab.owner.org/def/vocab1/3" OWNED="true" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#Concept"/>
  <RESOURCE_MAP ID="10" ACCESS_POINT_ID="8" DEPRECATED="true" IRI="http://vocab.owner.org/def/vocab1/7" OWNED="true" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#Concept"/>
  <RESOURCE_MAP ID="11" ACCESS_POINT_ID="8" DEPRECATED="false" IRI="http://some.other.org/def/vocab1/3" OWNED="false" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#Concept"/>
  <RESOURCE_MAP ID="12" ACCESS_POINT_ID="8" DEPRECATED="true" IRI="http://some.other.org/def/vocab1/7" OWNED="false" RESOURCE_TYPE="http://www.w3.org/2004/02/skos/core#Concept"/>
  <RESOURCE_MAP ID="13" ACCESS_POINT_ID="8" DEPRECATED="true" IRI="http://vocab.owner.org/def/vocab1/9" OWNED="true" RESOURCE_TYPE="http://www.w3.org/2002/07/owl#deprecated"/>
  <RESOURCE_MAP ID="14" ACCESS_POINT_ID="8" DEPRECATED="true" IRI="http://some.other.org/def/vocab1/9" OWNED="false" RESOURCE_TYPE="http://www.w3.org/2002/07/owl#deprecated"/>

</dataset>

=== au-research/ANDS-Vocabs-Toolkit/src/test/resources/deploy/test/tests/au.org.ands.vocabs.toolkit.test.arquillian.AllArquillianTests.testResourceMapTransformProvider3/input-dbunit.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "../../dbunit-toolkit-export-choice.dtd" >
<dataset>
  <VOCABULARIES
      ID="1"
      OWNER="ands"
      TITLE="testResourceMapTransformProvider3-1"
      SLUG="testresourcemaptransformprovider3-1"
      />
  <VOCABULARIES
      ID="2"
      OWNER="another"
      TITLE="testResourceMapTransformProvider3-2"
      SLUG="testresourcemaptransformprovider3-2"
      />
  <VERSIONS
      ID="1"
      VOCAB_ID="1"
      TITLE="v1" />
  <VERSIONS
      ID="2"
      VOCAB_ID="2"
      TITLE="v1" />
  <RESOURCE_OWNER_HOSTS
      ID="1"
      START_DATE="2016-09-16"
      END_DATE="9999-12-01"
      OWNER="ands"
      HOST="vocab.owner.org"
      />
  <RESOURCE_OWNER_HOSTS
      ID="2"
      START_DATE="2016-09-16"
      END_DATE="9999-12-01"
      OWNER="ands"
      HOST="second.owned.com"
      />
  <RESOURCE_OWNER_HOSTS
      ID="3"
      START_DATE="2016-09-16"
      END_DATE="9999-12-01"
      OWNER="ands"
      HOST="third.another.edu"
      />
  <RESOURCE_OWNER_HOSTS
      ID="4"
      START_DATE="2016-09-16"
      END_DATE="9999-12-01"
      OWNER="another"
      HOST="third.another.edu"
      />
  <TASK
      ID="1"
      VOCABULARY_ID="1"
      VERSION_ID="1"
      PARAMS="[
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''src/test/resources/input/au.org.ands.vocabs.toolkit.test.arquillian.AllArquillianTests.testResourceMapTransformProvider3/test-data1.ttl''
                },
                {
                  ''type'': ''IMPORT'',
                  ''provider_type'': ''Sesame''
                },
                {
                  ''type'': ''PUBLISH'',
                  ''provider_type'': ''SISSVoc''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''ResourceMap''
                }
              ]"
      />
  <TASK
      ID="2"
      VOCABULARY_ID="2"
      VERSION_ID="2"
      PARAMS="[
                {
                  ''type'': ''HARVEST'',
                  ''provider_type'': ''File'',
                  ''file_path'': ''src/test/resources/input/au.org.ands.vocabs.toolkit.test.arquillian.AllArquillianTests.testResourceMapTransformProvider3/test-data2.ttl''
                },
                {
                  ''type'': ''IMPORT'',
                  ''provider_type'': ''Sesame''
                },
                {
                  ''type'': ''PUBLISH'',
                  ''provider_type'': ''SISSVoc''
                },
                {
                  ''type'': ''TRANSFORM'',
                  ''provider_type'': ''ResourceMap''
                }
              ]"
      />
</dataset>
